# Generated by Django 5.2 on 2025-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_note_rating_delete_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeface',
            name='classification',
            field=models.CharField(choices=[('Serif', 'Serif'), ('Sans Serif', 'Sans Serif'), ('Slab Serif', 'Slab Serif'), ('Display', 'Display'), ('Script', 'Script'), ('Monospace', 'Monospace'), ('Handwritten', 'Handwritten'), ('Blackletter', 'Blackletter')], max_length=100),
        ),
    ]
