# Generated by Django 5.2 on 2025-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeface',
            name='pairings',
            field=models.ManyToManyField(to='main_app.pairing'),
        ),
    ]
